language: c
compiler: gcc

sudo: required

services:
  - docker

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y
    - cd cs220-redis-example
    - docker build -t redis-example . 
    - docker run -d -p 6379:6379 redis-example
    - docker container list
    - cd ../
    - git clone https://github.com/redis/hiredis.git
    - cd hiredis
    - make
    - sudo make install
    - sudo ldconfig
    - cd ../

script:
    # pwd: fulltext
    - make all && make -C tests clean all
    - cd tests/
    - ./test-fulltext

after_script:
    - echo "Finished Travis CI tests on /dev branch build"
