language: c
compiler: gcc
before_script:
    - echo "Running Travis CI tests on /dev branch build"

script:
    # pwd: fulltext
    - make all && make -C tests clean all
    - ./tests/test-fulltext

after_script:
    - echo "Finished Travis CI tests on /dev branch build"
