language: c
compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y

script:
    # pwd: fulltext
    - make all && make -C tests clean all
    - cd tests && ./test-fulltext

after_script:
    - echo "Finished Travis CI tests on /dev branch build"
