language: c
compiler: gcc

sudo: required

services:
  - docker

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y
    - git clone https://github.com/redis/hiredis.git
    - git submodule update --init --recursive
    - cd hiredis
    - make
    - sudo make install
    - sudo ldconfig
    - cd ../
    - sudo redis-server&

jobs:
  include:
    - stage: build
      script:
        - make clean all
    - stage: test
      script: 
        - make all && make -C tests clean all
        - tests/test-fulltext

after_script:
    - echo "Finished Travis CI tests on /dev branch build"
