language: c
compiler: gcc
before_script:
    - echo "Running Travis CI tests on /dev branch build"
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y

script:
    # pwd: fulltext
    - make all && make -C tests clean all
    - echo $TARGET_LIB
    - ./tests/test-fulltext

after_script:
    - echo "Finished Travis CI tests on /dev branch build"
